{{ config(
    materialized='table',
    replace=True
) }}
      
SELECT 
    TO_CHAR(NGAY_HACH_TOAN, 'YYYY-MM') AS THANG,
    NV.NHAN_VIEN_BAN,
    SUM(DOANH_THU) AS TONG_DOANH_THU
FROM 
    {{ source('BAI_TEST_SOURCE','NHAN_VIEN_TABLE') }} NV
JOIN 
    {{ source('BAI_TEST_SOURCE','DU_LIEU_BAN_HANG_TABLE') }} DL
ON
    NV.MA_NHAN_VIEN_BAN = DL.MA_NHAN_VIEN_BAN
GROUP BY 
    TO_CHAR(NGAY_HACH_TOAN, 'YYYY-MM'),
    NV.NHAN_VIEN_BAN
ORDER BY 
    THANG