
version: 2

sources:
    - name: BAI_TEST_SOURCE
      schema: BAI_TEST
      tables:
        - name: NHAN_VIEN_TABLE
        - name: DU_LIEU_BAN_HANG_TABLE

models:
  - name: revenue_by_month_saleman
    description: "Revenue by month and saleman"
    columns:
      - name: THANG
        description: "Month of the year"
      - name: NHAN_VIEN_BAN
        description: "Saleman name"
      - name: TONG_DOANH_THU
        description: "Revenue"

  - name: revenue_by_month_store
    description: "Revenue by month and store"
    columns:
      - name: THANG
        description: "Month of the year"
      - name: CHI_NHANH
        description: "Store name"
      - name: TONG_DOANH_THU
        description: "Revenue"

