SELECT 
    TO_CHAR(NGAY_HACH_TOAN, 'MM-YYYY') AS THANG,
    NV.NHAN_VIEN_BAN,
    SUM(DOANH_THU) AS TONG_DOANH_THU
FROM 
    NHAN_VIEN_TABLE NV
JOIN 
    DU_LIEU_BAN_HANG_TABLE DL
ON
    NV.MA_NHAN_VIEN_BAN = DL.MA_NHAN_VIEN_BAN
GROUP BY 
    TO_CHAR(NGAY_HACH_TOAN, 'MM-YYYY'),
    NV.NHAN_VIEN_BAN
ORDER BY 
    THANG